Repository DEFRA/waste-carriers-frontend, pull requests merged in 2019-03, with the labels that each got.

#195 Add Continuous Integration support
  .simplecov
  .travis.yml
  Gemfile
  Gemfile.lock
  README.md
  lib/tasks/ci_reporter.rake
  lib/tasks/coverage.rake
  spec/spec_helper.rb
  spec/support/simplecov.rb
Labels: housekeeping

#200 Update Money-rails to latest
  Gemfile.lock
  config/environment.rb
Labels: dependencies

#212 Fix how mongoid is specified in Gemfile
  Gemfile
  Gemfile.lock
Labels: housekeeping

#213 Update rails version and Gemfile declaration
  Gemfile
  Gemfile.lock
Labels: housekeeping

#214 Update rest-client and reference in Gemfile
  Gemfile
  Gemfile.lock
Labels: housekeeping

#215 Update devise and reference in Gemfile
  Gemfile
  Gemfile.lock
Labels: housekeeping

#218 Update privacy policy
  app/assets/stylesheets/_published_dates.css.scss
  app/assets/stylesheets/application.css.scss
  app/views/home/privacy.html.erb
  config/locales/en.yml
Labels: enhancement

#220 Fix up privacy policy after QA
  app/views/home/privacy.html.erb
  config/locales/en.yml
Labels: bug
