Repository DEFRA/waste-carriers-frontend, pull requests merged in 2019-12, with the labels that each got.

#277 Remove approve and refuse links from backend dashboard
  app/views/registrations/index.html.erb
  config/routes.rb
Labels: enhancement

#278 Remove renewal extension message
  app/views/pages/renewal_extension.html.erb
  config/locales/en.yml
Labels: housekeeping

#281 Update destination of the order copy cards link
  app/helpers/registrations_helper.rb
  app/views/registrations/index.html.erb
Labels: enhancement

#282 Fix issues with links to new apps
  app/controllers/registrations_controller.rb
  app/helpers/registrations_helper.rb
  app/models/concerns/can_be_renewed.rb
  app/views/registrations/index.html.erb
  config/application.rb
  spec/helpers/registrations_helper_spec.rb
  spec/models/concerns/can_be_renewed.rb
Labels: bug
