Repository DEFRA/waste-carriers-frontend, pull requests merged in 2019-04, with the labels that each got.

#221 Fix broken link to NI waste carriers service
  app/views/register_in_northern_ireland/show.html.erb
Labels: bug

#223 Update privacy policy date
  app/views/home/privacy.html.erb
Labels: enhancement

#224 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping

#227 Add email interception and retrieval
  .env.example
  app/controllers/last_email_controller.rb
  config/application.rb
  config/initializers/last_email_cache.rb
  config/routes.rb
  lib/last_email_cache.rb
  spec/lib/last_email_cache_spec.rb
  spec/requests/last_email_spec.rb
  spec/support/helpers.rb
Labels: enhancement

#228 Fix last email cache body extraction
  app/mailers/test_mailer.rb
  app/views/test_mailer/test_email.html.erb
  app/views/test_mailer/test_email.text.erb
  lib/last_email_cache.rb
  spec/lib/last_email_cache_spec.rb
  spec/requests/last_email_spec.rb
  spec/support/helpers.rb
Labels: bug

#229 Refactor the rake test email task
  app/mailers/registration_mailer.rb
  app/views/registration_mailer/test_email.text.erb
  config/application.rb
  lib/tasks/email.rake
Labels: housekeeping

#232 Add test coverage for correct handling of 404 errors
  spec/requests/page_not_found_spec.rb
  spec/support/error_responses_helper.rb
Labels: bug

#231 Remove call to byebug
  app/helpers/worldpay_helper.rb
Labels: housekeeping

#230 Remove byebug and swap it with pry-byebug
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: housekeeping
